# dev only
-
  environment:
    package_semantic_version: 1.0.7
  version: $(package_semantic_version).{build}
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - dev
  skip_tags: true
  skip_commits:
    files:
      - .gitignore
      # - appveyor.yml
      - LICENSE
      - README.md
      - Settings.StyleCop
      - commonservicelocator.sln
      - commonservicelocator.sln.DotSettings
      # - '**/*.csproj'
  image: Visual Studio 2017
  configuration: Debug
  platform: Any CPU
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '$(package_semantic_version).0'
  nuget:
    disable_publish_on_pr: true
  before_build:
  - cmd: nuget.exe restore .\commonservicelocator.sln -Verbosity Detailed -NonInteractive
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    verbosity: minimal
  artifacts:
  - path: .\src\Microsoft.Practices.ServiceLocation\**\*.nupkg
    name: commonservicelocator

# release Only
-
  environment:
    package_semantic_version: 1.0.7
    solution_name: commonservicelocator
  version: $(package_semantic_version).{build}
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - release
  skip_tags: true
  skip_commits:
    files:
      - .gitignore
      # - appveyor.yml
      - LICENSE
      - README.md
      - Settings.StyleCop
      - commonservicelocator.sln
      - commonservicelocator.sln.DotSettings
      # - '**/*.csproj'
  image: Visual Studio 2017
  configuration: Release
  platform: Any CPU
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '$(package_semantic_version).0'
  nuget:
    disable_publish_on_pr: true
  before_build:
  - cmd: nuget.exe restore .\commonservicelocator.sln -Verbosity Detailed -NonInteractive
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    verbosity: minimal
  artifacts:
  - path: .\src\Microsoft.Practices.ServiceLocation\**\*.nupkg
    name: commonservicelocator
  deploy:
  - provider: Environment
    name: NuGet for CommonServiceLocator
